---
title: "PAI Lab"
output: html_document
---


&nbsp;

At the 2023 annual conference of the International Communication Association, I had the opportunity to propose and moderate a panel on managing lab research. [Autumn Edwards](https://wmich.edu/communication/directory/edwards), [Grace Sun Joo Ahn](https://grady.uga.edu/faculty/sun-joo-grace-ahn/), [Matthew Lombard](https://klein.temple.edu/directory/matthew-lombard-lombard), and [Tony Liao](https://dot.egr.uh.edu/departments/ilt/people/faculty/liao-tony) shared their lab management and research experience, which sparked my establishment and direction of the lab - <font color="green">**Presence and Artificial Intelligence (PAI) Lab**</font>. Drawing on an analogy with the pronunciation and significance of “<font color="green">***π***</font>”, our lab symbolizes the commitment to exploring infinite and non-recurring possibilities for emerging technology research.

The PAI Lab aims at conducting research on users’ perceptions of, interactions with, and evaluations of presence-evoking emerging technologies, such as social robots, virtual agents, chatbots, virtual reality, and augmented reality. The PAI Lab also delves into topics such as explainable AI (XAI), Science and Technology Studies (STS), and ubiquitous computing. 

Revolving around both the science and the methods of artificial intelligence, our lab seeks to conduct theoretically robust and methodologically innovative research, with the support of the technologies like:\
*Aldebaran Robot NAO*\
*Double II Telepresence robot*\
*Meta Quest Pro*\
*UBTech Robot Alpha*\
*Robot Eilik*\

&nbsp;
&nbsp;

Our lab members are:

[Fanjue Liu](https://www.jou.ufl.edu/staff/fanjue-liu-2/)

Fanjue Liu is a doctoral student at the the University of Florida. Her research investigates how people perceive and interact socially with emerging technologies such as virtual humans. Specifically, she investigates how people use different psychological patterns to interact with virtual influencers, how the emergence of virtual influencers changes the dynamics of influencer marketing, and whether virtual influencers can be considered a viable substitute for human influencers.\

[Xiaobei Chen](https://www.jou.ufl.edu/staff/xiaobei-chen-2/)

Xiaobei Chen is a doctoral student at the College of Journalism and Communications at the University of Florida. Her research focuses on using emerging technologies to promote health equity and to conduct communication skill training in healthcare.\

[Lynn Li](https://www.jou.ufl.edu/staff/jiayue-lynn-li/) 

(bio to be added)\

[Yunxiao Chen](https://www.jou.ufl.edu/staff/yunxiao-chen/)

(bio to be added)\

[Loren Ruffin](https://www.linkedin.com/in/loren-ruffin/) 

Loren Ruffin was a Professional Master's student in the CJC and completed an M.A. in Mass Communication. Prior to attending UF, she received a B.S. in Communication, with a concentration in Journalism, from East Carolina University. Her study interests included human-machine communication, digital user experiences, and diversity, equity, and inclusion in digital products. As part of her capstone project, she designed and programmed a virtual reality vocabulary game focused on accessibility specifically for deaf and hard-of-hearing users. Post-graduation she is currently a content designer for Uber's Safety UX team, helping to design experiences that aim to keep earners and consumers safe on the app.\



