---
title: "Publications"
output:
  html_document: default
  pdf_document: default
---

<font color="red">Latest update: 05/31/2025.</font>

<font color="green">**Peer-Reviewed Journal Articles:**</font>

Xu, K., Chen, Y., Li, J., Liao, T., & Chan-Olmsted, S. (2025). Tracked but not trapped: Negotiating body tracking technologies for embodiment and privacy protection in VR. *Computers in Human Behavior, 170,* 108706. [PDF](publications/Xu et al. 2025 Tracked but not trapped.pdf)

Liao, T., Xu, K., & Spencer, B. (2025). Is it time for augmented reality theory? Identifying challenges and pathways for theoretical development. *Journal of Media Psychology, 37.* [PDF](publications/Liao et al. 2025 JMP.pdf)

Shi, J., Xia, X., Zhuang, H., & Li, Z., & Xu, K. (2025). Empowering individuals to adopt artificial intelligence for health information seeking: A latent profile analysis among users in Hong Kong. *Social Science & Medicine, 375,* 118059. [PDF](publications/Shi et al. 2025 Social Science & Medicine.pdf)

Xu, K., & Shi, J. (2024). Visioning a two-level human-machine communication framework: Initiating conversations between explainable AI and communication. *Communication Theory, 34,* 216-229. [PDF](publications/Xu & Shi 2024 XAI & communication.pdf)


Xu, K., Chen, X., Liu, F., & Huang, L. (2024). What did you hear and what did you see? Understanding the transparency of facial recognition and speech recognition systems during human-robot interaction. *New Media & Society.* Online First. [PDF](publications/xu-et-al-2024-what-did-you-hear-and-what-did-you-see-understanding-the-transparency-of-facial-recognition-and-speech.pdf) 

Kim, J., Jin, X., Xu, K., Chen, X., & Yang, H. (2024). What do people say about Replika, an AI chatot, on social media? Investigating diverse perspectives on the implications of Replika through a topic modeling analysis. *The Social Science Journal.* [pdf](publications/Kim et al 2024 What do people say about Replika  an AI chatbot  on social media  Investigating diverse perspectives on the implications of Replika through a topic mo.pdf)

Kim, J., Kelly, S., & Xu, K. (2024). Understanding the influence of student expectations of instructor immediate behaviors on AI-based education: The moderating role of social presence of AI instructors. *Communication Quarterly, 72,* 421-438. [pdf](publications/Kim et al 2024 Understanding the influence of student expectations of instructor immediate behaviors on AI-based education  the moderating role of social presence of.pdf) 

Xu, K. (2023). A mini imitation game: How individuals model social robots via behavioral outcomes and social roles. *Telematics & Informatics, 78,* 101950. [PDF](publications/Xu 2023 mini imitation game.pdf)

Xu, K., Chen, M., & You, L. (2023). The hitchhiker's guide to a credible and socially present robot: Two meta-analyses of the power of social cues in human-robot interaction. *International Journal of Social Robotics.*  [PDF](publications/Xu et al. 2023 Meta-Analyses.pdf)

Kim, J., Merrill, K., Jin, X., Collins, C., & Xu, K. (2023). Trust, perceived usefulness, and intentions to adopt robotic health advisors for physical and relational health issues. *The Social Science Journal.* [PDF](publications/Kim et al 2023 Trust  perceived usefulness  and intentions to adopt robotic health advisors for physical and relational health issues.pdf) 

Kim, J., Merrill, K., Xu, K., & Collins, C. (2023). My health advisor is a robot: Understanding intentions to adopt a robotic health advisor. *International Journal of Human-Computer Interaction.* [PDF](publications/Kim et al. 2023 My Health Advisor is a Robot Understanding Intentions to Adopt a Robotic Health Advisor.pdf)

Liu, W., Xu, K., & Yao, M. (2023). Can you tell me about yourself? The impacts of chatbot names and communication contexts on users’ willingness to self-disclose information in human-machine conversations. *Communication Research Reports, 40*, 122-133. [PDF](publications/Liu et al. 2023.pdf)  


Xu, K., Chan-Olmsted, S., & Liu, F. (2022). Smart speakers require smart management: Two routes from user gratifications to privacy settings. *International Journal of Communication, 16,* 192-214. [PDF](publications/Xu et al. 2022 Smartspeakers.pdf)


Xu, K., Chen, X., & Huang, L. (2022). Deep mind in social responses to technologies: A new approach to explaining the Computers are Social Actors phenomena. *Computers in Human Behavior, 134,* 107321. [PDF](publications/Xu et al. 2022 Deep mind in social responses.pdf)


Kim, J., Merrill, K., Xu, K., & Kelly, S. (2022). Perceived credibility of an AI instructor in online education: The role of social presence and voice features. *Computers in Human Behavior, 136,* 107383. [PDF](publications/Kim et al. 2022 Perceived credibility of an AI instructor.pdf)


Kim, J., Merrill, K., Xu, K., & Sellnow, D. (2022). Embracing AI-based education: Perceived social presence of human teachers and expectations about machine teachers in online education. *Human-Machine Communication, 4,* 169-184. [PDF](https://stars.library.ucf.edu/cgi/viewcontent.cgi?article=1084&context=hmc#page=169) 


Kim, J., Xu, K., Merrill, K. (2022). Man vs machine: Human responses to an AI newscaster and the role of social presence. *The Social Science Journal.* [PDF](publications/Kim et al 2022 Man vs machine.pdf)


Kim, J., Merrill, K., Xu, K., & Sellnow, D. (2021). I like my relational machine teacher: An AI instructor’s communication styles and social presence in online education. *International Journal of Human-Computer Interaction.* [PDF](publications/Kim et al. 2021 I Like My Relational Machine Teacher An AI Instructor s Communication Styles and Social Presence in Online Education.pdf)


Lombard, M., & Xu, K. (corresponding author) (2021). Social responses to media technologies: The Media are Social Actors paradigm. *Human-Machine Communication, 2,* 29-55. [PDF](https://stars.library.ucf.edu/cgi/viewcontent.cgi?article=1030&context=hmc) 


Xu, K., Liu, F., Mou, Y., Wu, Y., Zeng, J., & Schafer, M. (2020). Using machine learning to learn machines: A cross-cultural study of users’ responses to machine-generated art works. *Journal of Broadcasting and Electronic Media, 64,* 566-591. [PDF](publications/Xu et al. 2020 Using Machine Learning to Learn Machines A Cross Cultural Study of Users Responses to Machine Generated Artworks.pdf)


Xu, K. (2020). Language, modality, and mobile media use experiences: Social responses to smartphone cues in a task-oriented context. *Telematics and Informatics, 48,* 101344 [PDF](publications/Xu 2020 Mobile phone study.pdf)


Xu, K., & Liao, T. (2020). Explicating cues: A typology for understanding emerging media technologies. *Journal of Computer-Mediated Communication, 25,* 32-43. [PDF](publications/Xu & Liao Explicating Cues JCMC.pdf); [Long Version](publications/ICA paper 5.30 Kun & Tony.pdf)


Kim, J., Merrill, K., Xu, K., & Sellnow, D. (2020). My teacher is a machine: Understanding students’ perception of AI teaching assistants in online education. *International Journal of Human-Computer Interaction, 36,* 1902-1911. [PDF](publications/Kim et al. 2020.pdf)


Liao, T., & Xu, K. (2020). A process approach to understanding multiple open source innovation contests: Assessing the contest structures, execution, and participant responses in the Android Developer Challenges. *Information and Organization, 30.* [PDF](publications/Liao & Xu Android contest I&O .pdf)


Liao, T., Yang, H., Lee, S., Xu, K., & Bennett, S. (2020). Augmented criminality: How people process in-situ augmented reality crime information in relation to space/place. *Mobile Media & Communication, 8,* 360-378. [PDF](publications/liao et al. augmented reality.pdf)


Wu, Y., Mou, Y., Li, Z., & Xu, K. (2020). Investigating American and Chinese subjects’ explicit and implicit perceptions of AI-generated artistic work. *Computers in Human Behavior, 104,* 106186. [PDF](publications/Wu et al. (2020) Chinese American implicit and explicit.pdf)


Xu, K. (2019). First encounter with robot Alpha: How individual differences interact with vocal and kinetic cues in users’ social responses. *New Media & Society, 21,* 2522-2547. [PDF](publications/Xu 2019 Robot alpha.pdf)


Mou, Y., Xu, K., & Xia, K. (2019). Unpacking the black box: Examining the (de)gender categorization effect in human-machine communication. *Computers in Human Behavior, 90,* 380-387. [PDF](publications/Mou Xu Xia gender decategorization effect.pdf)


Mou, Y., Shi, C., Shen, T., Xu, K. (2019). A systematic review of the personality of robot: Mapping its conceptualization, operationalization, contextualization, and effects. *International Journal of Human-Computer Interaction, 36*, 591-605. [PDF](publications/Mou et al 2019 A Systematic Review.pdf)


Xu, K. (2018). Painting Chinese mythology: Varying touches on the magazine covers of Time, The Economist, Der Spiegel, and China Today. *International Communication Gazette, 80,* 135-157. [PDF](publications/Xu_Painting Chinese Methology.pdf)


Xu, K. (2018). Location speaks: Using GIS approach and Weibo check-in data to understand information communication in China. *China Media Research, 14,* 29-43. [PDF](publications/Xu Location speaks.pdf)


Steiner, E., & Xu, K. (2018). Binge-watching motivates change: How the uses and gratifications of streaming video viewers are challenging traditional audience research. *Convergence: The International Journal of Research into New Media Technologies, 26*(1), 82-101. [PDF](publications/Steiner_Xu_bingewatching.pdf)


Xu, K., & Lombard, M. (2017). Persuasive computing: Feeling peer pressure from multiple computer agents. *Computers in Human Behavior, 74,* 152-162. [PDF](publications/Xu_Lombard_Persuasive computing.pdf)


Mou, Y. & Xu, K. (2017). The media inequality: Comparing the initial human-human and human-AI social interactions. *Computers in Human Behavior, 72,* 432-440. [PDF](publications/Yi Xu_Media Inequality.pdf)


Xu, K., Lin, M., & Haridakis, P. (2015). Being addicted to Chinese Twitter: Exploring the roles of users’ expected outcomes and deficient self-regulation in social network service addiction. *China Media Research, 11*(2), 1-16. [PDF](publications/Xu et al -Being_addicted_to_Chinese_Twit.PDF)


<font color="green">**Book Chapters:**</font>

Lombard, M., Xu, K., & Melissa, S. (2024). Future presence: Living with humanlike robots. In L. Fortunati & A. Edwards (Eds.), *De Gruyter handbook of robots in society and culture.* De Gruyter: Berlin.

Xu, K., Liu, F., Chen, X., & Lombard, M. (2023). The Media are Social Actors paradigm and beyond: Theory, evidence, and future research. In S. Nah (Ed.), *Research handbook on artificial intelligence and communication,* pp. 337-354. Edward Elgar. 

Xu, K., & Jeong, D. (2023). Social presence. In A. Guzman, R. McEwen, & S. Jones (Eds.), *The handbook of human-machine communication,* pp.287-293. Sage. 

Lombard, M., Lee, S., Sun, W., Xu, K., & Yang, H. (2017). Presence theory. In P. Roessler, C. Hoffner, & L. Van-Zoonen (Eds.), *International encyclopedia of media effects,* pp. 1-13. Wiley-Blackwell. [PDF](publications/Lombard et al. presence theory.pdf)

Mou, Y., Xu. K. (2017). Human-computer communication: An emerging communication realm. In B. Li., & Y., Mou. (Eds.), *Future media: Opportunities and challenges,* pp. 42-51. Shanghai: Shanghai Jiao Tong University Press.

Wallace, M., & Knobel, B. (2017). Heat and light: Advice for the next generation of journalists. (C. Hua, & K. Xu, Trans.). PRC: China Renmin University Press Co., LTD. [Link to Douban](https://book.douban.com/subject/26972289/)


<font color="green">**Conference Proceedings:**</font>

Cheon, S., Stanbury, A., Lam, J., Xu, K., Kang, H. (2025). Virtual tutors for science labs: Exploring the impact of GPT integration and 3D tutor avatars on student engagement and learning outcomes. ACM SIGCHI Conference on Computer-Supported Cooperative Work & Social Computing (CSCW).

Yerebakan, M. O., Hao, S., Xu, K., Gheisari, M., Jeelani, I., & Hu, B. (2021). Effect of illumination on human drone interaction tasks: An explorative study. Proceedings of the Human Factors and Ergonomics Society Annual Meeting, 65(1), 1485-1489. Sage. 

Xu, K. (2018). Action speaks louder than words: A preliminary study of users’ social responses to social robots’ movements and voices. Proceedings of the 18th Conference of the International Society for Presence Research. ISBN: 978-0-9792217-6-7

Xu, K., & Lombard, M. (2018). Media are social actors: The role of social cues. Proceedings of the 18th Conference of the International Society for Presence Research. ISBN: 978-0-9792217-6-7

Lombard, M., Selverian, M., Steiner, E., Xu, K., & Yang, H. (2018). Implications of presence portrayals in popular culture: Challenges for the future of technology and humanity. Proceedings of the 18th Conference of the International Society for Presence Research. ISBN: 978-0-9792217-6-7

Liao, T., Yang, H., Lee, S., Xu, K., Feng, P., & Bennett, S. (2017). Augmented criminality: How mobile augmented reality crime overlays affect people’s sense of place. AoIR Selected Papers of Internet Research, 6. 
