---
title: "Independent Teaching Experiences"
---

**University of Florida (2019-present):**

 - Spring 2023: MMC 6936 Computer-Mediated Communication (Graduate level)
 - Spring 2023: RTV 4930 Media User Experience 
 - Fall 2022: MMC 6936 Human-Machine Communication (Graduate level)
 - Fall 2022: RTV 4930 Media User Experience 
 - Spring 2022: MMC 6936 Computer-Mediated Communication (Graduate level) [reading list](Files/CMC readings.pdf)
 - Spring 2022 RTV 3405 Media and Society (~70 students)
 - Fall 2021: MMC 6936 Human-Machine Communication (Advanced graduate level) [reading list](Files/HMC reading list.pdf)
 - Fall 2021: RTV 3405 Media and Society (~50 students)
 - Spring 2021: RTV 3405 Media and Society (~200 students)
 - Spring 2021: MMC 6936 Computer-Mediated Communication (Graduate level)
 - Fall 2020: MMC 6936 Human-Machine Communication (Advanced graduate level)
 - Fall 2020: RTV 3405 Media and Society (~70 students)
 - Spring 2020: MMC 6936 Computer-Mediated Communication (Graduate level)
 - Spring 2020: RTV 3405 Media and Society (~110 students)
 - Fall 2019: RTV 3405 Media and Society (~130 students)

**Temple University (2016-2019):**

- Spring 2019: MSP 3471 Media and Cultural Differences
- Spring 2019: MSP 2741 Internet Studies and Web Authoring (section 701), online course
- Spring 2018: MSP 4541 Mobile Media (section 401)
- Spring 2018: MSP 4541 Mobile Media (section 001)
- Fall 2017: MSP 4541 Mobile Media (section 001)
- Fall 2017: MSP 4541 Mobile Media (section 002)
- Summer 2017: MSP 3421 Technology and Culture
- Spring 2017: MSP 3421 Technology and Culture
- Spring 2017: MSP 4541 Mobile Media
- Fall 2016: MSP 0821 Future of Your TV

**Based on my teaching specialities, in addition to the courses listed above, I am willing to offer courses related to**

- Psychological Processing of Media
- Media Theories
- Quantitative Research Methods (e.g., survey design, experiment design, basic inferential statistics)
- Advanced Quantitative Research Methods (e.g., multivariate analyses, structural equation modeling, multilevel modeling)

**Doctoral committees**

- Co-chair, Fanjue Liu, UFCJC
- Chair, Jiayue Li, UFCJC
- Member, Andrew Maxim, Department of Computer and Information Science and Engineering, UF
- Member, Weizi Liu, Informatics/Communication and Media, University of Illinois Urbana-Champaign 
- Member, Heidi Makady, UFCJC
- Member, Yoo Jin Chung, UFCJC, graduated 2022
- Member, Larissa Neuburger, Department of Tourism, Hospitality, and Event Management, UF, graduated 2021

**Master's committees**

- Chair, Yunxiao Chen, UFCJC
- Chair, Loren Ruffin, UFCJC, graduated 2023
- Member, Junyi Wu, UFCJC, graduated 2021
- Member, Nam Gwiwon, UFCJC

